# Generated by Django 4.2.16 on 2025-11-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('tulipanes', 'Tulipanes'), ('girasoles', 'Girasoles'), ('lavanda', 'Lavanda'), ('panda', 'Panda'), ('pinguino', 'Pingüino'), ('ballena', 'Ballena'), ('shrek', 'Shrek'), ('stitch', 'Stitch'), ('hello_kitty', 'Hello Kitty'), ('kuromi', 'Kuromi'), ('caroline', 'Caroline'), ('lilo', 'Lilo'), ('rapunzel', 'Rapunzel'), ('sirenita', 'La Sirenita'), ('cenicienta', 'Cenicienta'), ('llavero_fresa', 'Llavero de Fresa'), ('llavero_cereza', 'Llavero de Cereza'), ('llavero_sandia', 'Llavero de Sandia')], max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('flores', 'Flores'), ('animales', 'Animales'), ('personajes', 'Personajes'), ('princesas', 'Princesas'), ('llaveros', 'Llaveros de Frutas')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiencia compartida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='members.tutorial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='members.usuario')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
