# Generated by Django 4.2.16 on 2025-11-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_tutorial_evidencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidencia',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
