# Generated by Django 4.2.16 on 2025-11-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_perfilusuario_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
