# Generated by Django 4.2.16 on 2025-11-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_delete_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
