# Generated by Django 4.2.16 on 2025-11-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.CharField(max_length=100, verbose_name='Tutorial completado')),
                ('dificultad', models.CharField(choices=[('muy_facil', 'Muy fácil'), ('facil', 'Fácil'), ('moderado', 'Moderado'), ('desafiante', 'Desafiante'), ('muy_dificil', 'Muy difícil')], max_length=20, verbose_name='Nivel de dificultad')),
                ('tiempo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo que tomó')),
                ('experiencia', models.TextField(verbose_name='Experiencia personal')),
                ('recomendacion', models.CharField(choices=[('si', 'Sí, definitivamente'), ('tal_vez', 'Tal vez, depende'), ('no', 'No lo recomendaría')], max_length=10, verbose_name='¿Lo recomendarías?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.usuario')),
            ],
            options={
                'verbose_name': 'Experiencia de Tutorial',
                'verbose_name_plural': 'Experiencias de Tutoriales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
