# Generated by Django 4.2.16 on 2025-11-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_experienciatutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCrochet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo para respuesta')),
                ('tipo_consulta', models.CharField(choices=[('tecnica', 'Técnica específica'), ('patron', 'Interpretación de patrón'), ('materiales', 'Selección de materiales'), ('problema', 'Problema con un proyecto'), ('diseno', 'Diseño personalizado'), ('otro', 'Otro')], max_length=20)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('proyecto', models.CharField(max_length=100, verbose_name='Proyecto o técnica')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('urgencia', models.CharField(choices=[('baja', 'Baja (Puede esperar)'), ('media', 'Media (En los próximos días)'), ('alta', 'Alta (Lo antes posible)')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('respondida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.usuario')),
            ],
        ),
    ]
